# Site settings
title: petertian
email: maishu@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  a man from jxRCB
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bigtien.com" # the base hostname & protocol for your site
github_username:  bigtien

# Build settings
markdown: kramdown
